### ISSUE TITLE
Double quotation marks are not correctly backslashed in the dumped toml file

### ISSUE THREAD

**Issue by eternal-flame-AD** [netlify/netlify-playground#34]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

Double quotation marks are not correctly backslashed in the dumped `toml` file

**- If the current behavior is a bug, please provide the steps to reproduce.**

Dump the following `_headers` file, which is valid and the double quotation marks would appear on the actual header
```
/*
    Public-Key-Pins-Report-Only: pin-sha256="[redacted]"; pin-sha256="[redacted]"; max-age=8640000; report-uri="[redacted]"
```
I got the following result
```toml
[[headers]]
for = "/*"
[headers.values]
Public-Key-Pins-Report-Only = "pin-sha256="[redacted]"; pin-sha256="[redacted]"; max-age=8640000; report-uri="[redacted]""
```

**- What is the expected behavior?**

The double quotation should be correctly escaped according to [the toml specification](https://github.com/toml-lang/toml#string), e.g.:

```toml
[[headers]]
for = "/*"
[headers.values]
Public-Key-Pins-Report-Only = "pin-sha256=\"[redacted]\"; pin-sha256=\"[redacted]\"; max-age=8640000; report-uri=\"[redacted]\""
```
